### auth routes
### signup user
POST http://localhost:8000/auth/signup
Content-Type: application/json

{
    "username":"Dougie Hawes",
    "email":"doughawes42@gmail.com",
    "password":"Wittgenstein42",
    "password2":"Wittgenstein42"
}

### activate user
POST http://localhost:8000/auth/activate
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkRvdWdpZSBIYXdlcyIsImVtYWlsIjoiZG91Z2hhd2VzNDJAZ21haWwuY29tIiwicGFzc3dvcmQiOiJXaXR0Z2Vuc3RlaW40MiIsImlhdCI6MTU5ODk0NjI0NSwiZXhwIjoxNTk4OTQ2ODQ1fQ.ZFzFOUxJ4Hl74997oX6jlR6LQw3raL27DzniEmPGPS4"
}

### sign in user
POST http://localhost:8000/auth/signin
Content-Type: application/json

{
    "email":"elliot@fsociety.net",
    "password":"Wittgenstein42"
}

### sign out user
POST http://localhost:8000/auth/signout

### image routes
GET http://localhost:8000/image

### profile routes
POST http://localhost:8000/profile/edit
Content-Type: application/json
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWY0ZGZhZDYxYmM2ZTU0NTc4NGQxN2RlIn0sImlhdCI6MTU5ODk0NzY4OSwiZXhwIjoxNTk4OTgzNjg5fQ.LzDqEhDGchQYPY7EmyI8ZSmHueEsjTZp4Ek4kKZERWg

{
    "location":"New York",
    "bio":"I'm an ethical hacker by profession, hacktivist by lifestyle"
}